### ISSUE TITLE
Share Decentraland app using Expo

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#101]
@marcelomorgado We can try this even before releasing the app through TestFlight

**Comment by marcelomorgado** [comment]
https://expo.io/@marcelo.morgado/tasit-demo

**Comment by pcowgill** [comment]
Awesome, thanks!

Until this is done: https://expo.canny.io/feature-requests/p/better-team-collaboration-tools-or-workflow

Let’s create a user named tasit to publish the app under and share the password (outside of GitHuB)

**Comment by pcowgill** [comment]
@marcelomorgado Can you share permissions to view the app you published with the the expo user `pcowgill`? Thanks! I don’t think I can view it in the app until that is done.

**Comment by marcelomorgado** [comment]
Weird... The app is public, can you see the qrcode?
Has no option to share permissions. Are you sure that exists such an option?
Could you create the `tasit` user (since I have no tasit email account)?

**Comment by pcowgill** [comment]
Maybe it’s that we didn’t build it for iOS?

Yep, I’ll create the user

**Comment by pcowgill** [comment]
![aada11d6-64c4-4d06-8b87-b6fc75d48916](https://user-images.githubusercontent.com/2731712/52719885-25489d00-2f6c-11e9-932c-f1c3bed328ea.png)

**Comment by marcelomorgado** [comment]
> Maybe it’s that we didn’t build it for iOS?

Yes, you are right. I'll build for ios now.

> Yep, I’ll create the user

:+1:

**Comment by pcowgill** [comment]
I opened the app using the button since I’m on iOS.

**Comment by pcowgill** [comment]
![0bdbbe4d-a263-475d-bd9a-d4d696ce5f71](https://user-images.githubusercontent.com/2731712/52721059-73f73680-2f6e-11e9-81c3-e47e223658e2.png)

**Comment by marcelomorgado** [comment]
Yeah, I haven't built the iOS version yet, the Expo is asking for an Apple ID. How to proceed?

**Comment by pcowgill** [comment]
Ah okay, you can pause there for now and work on something else? I’ll set up an Apple id

**Comment by marcelomorgado** [comment]
Sure. :+1:

**Comment by pcowgill** [comment]
Sharing the demo app using Expo can only be done on Android with the new iOS rules. So I think we can mark this as complete.

Although maybe we should re-publish the demo app under the `tasit` expo username before closing this.

**Comment by pcowgill** [comment]
Also we should republish it now that I renamed the slug to `io.tasit.decentraland` in https://github.com/tasitlabs/tasit/pull/135

**Comment by pcowgill** [comment]
https://expo.io/@tasit/tasit-decentraland

**Comment by marcelomorgado** [comment]
This issue can be closed?

**Comment by pcowgill** [comment]
Yep!
