### ISSUE TITLE
Move actions and reducers to a folder in demo app called store or redux

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#102]

**Comment by pcowgill** [comment]
The thinking behind this is that once there are this many files in a directory, it can get a little overwhelming deciding where to start when first looking at the folder

<img width="994" alt="screenshot 2019-02-14 08 32 51" src="https://user-images.githubusercontent.com/2731712/52797480-37d9d980-3033-11e9-84a8-699deeee8f67.png">

**Comment by marcelomorgado** [comment]
The name of folder could be `actions` ?

**Comment by marcelomorgado** [comment]
Nevermind, I think that `redux` is a better name.

**Comment by pcowgill** [comment]
Okay, I agree. Thanks. Or maybe something like "state" if we want to keep it generic and not specific to redux in case we move some things over to context API.
