### ISSUE TITLE
Have the default decentraland app config in a build point to testnet but make the default for the local development using localhost

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#111]
I think we will probably want an option to run even the `decentraland` one with localhost too, just not as the default.

Once this is done: https://github.com/tasitlabs/TasitSDK/issues/135

Credit to @marcelomorgado for this suggestion

**Comment by pcowgill** [comment]
@marcelomorgado I think the rough original intent of this issue is complete, even if it’s not done exactly as the issue is worded

**Comment by marcelomorgado** [comment]
Agree

**Comment by pcowgill** [comment]
Re-opening this based on our discussion on Slack

**Comment by marcelomorgado** [comment]
@pcowgill commented:

> It would be nice if `npm start` defaulted the app to using the `development` config and not `default`

> Perhaps by `npm start` passing a flag through that sets a var that chooses which config to use
