### ISSUE TITLE
Add a test to the test suite confirming that Account.create() works in React Native env

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#12]

**Comment by pcowgill** [comment]
This makes sure that the shims we used with `ethers.js` over in the Tasit SDK made it through to here properly and are working in React Native now that there's this indirection in where they come from.

**Comment by pcowgill** [comment]
@marcelomorgado Thanks for this detailed info! That test case is what I was picturing.

I think in general having as many shallow tests as possible is considered good practice.

For most smaller components that change based on variable data, we can test those just by faking that data as input to a pure component. So we won't have too many tests where we need to manually call componentDidMount to trigger data generation.

Enzyme is what I've used in the past when I do need to manually interact with the virtual DOM.

So let's mostly use the non-Enzyme approach, but use Enzyme for this specific case you brought up. (So that would mean using a little of both open WIP branches).

In the Enzyme README they say Enzyme v3 is supposed to support React 16.

I followed through that path of comments you linked to. Let's create an issue to remember to remove the modifiied preprocessor whenever they get this working.

I haven't encountered this particular issue with react-native before, mostly because I've mostly worked with older versions.

Here are some slides I like on testing React (and React Native) applications https://docs.google.com/presentation/d/1VRyWAZ0qSmJgcCEpl7XX68eoVf7890H1nkPWM0jkToY/edit#slide=id.p5

**Comment by pcowgill** [comment]
@marcelomorgado Given that info, which WIP will you plan on working on?

**Comment by marcelomorgado** [comment]
Snapshots

I’ve found three ways to do that:
1. Using react-test-renderer create
2. Using react-test-renderer/shallow
3. Using enzyme shallow

I’ve used Jest+Enzyme to generate snapshots. **Motivations:**
- The attached presentation uses it;
- react-test-renderer (renderer.create) is rendering component entirely creating a large snapshot (there is a lint rule to prevent large snapshots) and testing child components;
- The Enzyme has a better shallow API.

It isn’t working perfectly yet. There is a caveat:

Snapshots don’t recognize some react-native components (i.e., View, Image are saved as Component)?
**Issue**: https://github.com/facebook/react-native/pull/22417
**Status**: Solved on react-native v0.57.8 (2018/12/13) [release note](https://github.com/facebook/react-native/releases/tag/v0.57.8)
**Solution**: Wait for new Expo release with RN v0.57.8. Current `expo` package is 31.0.6 (2018/11/30)

**Refs**
https://reactjs.org/docs/shallow-renderer.html
https://www.npmjs.com/package/eslint-plugin-jest
https://airbnb.io/enzyme/docs/api/shallow.html

**Comment by marcelomorgado** [comment]
**Enzyme simulate press w/ async function**

I’ve faced the problem related to this issue: https://github.com/airbnb/enzyme/issues/1153

`wrapper.simulate(‘press’)` is working but it has been executed after test case (I’ve tried out using setTimeout to check it, but problem stills). Code sample:

**EthereumSignUpForm.test.js**
```
it("creates a wallet - pressing button", async () => {
    const wrapper = shallow(<EthereumSignUpForm />);

    expect(wrapper.state("address")).toEqual("");

    wrapper
      .find("Button")
      .find({ title: "Continue" })
      .simulate("press");

    wrapper.update();

    console.log("Address value: " + wrapper.state("address"));

    expect(wrapper.state("address")).not.toEqual("");
  });
```
**EthereumSignUpForm.js**
```
 createAccount = async () => {
    // TODO: Remove await when SDK 0.0.3 is out
    const wallet = await Account.create();
    console.log("Button pressed");
    this.setState({ address: wallet.address });
  };
```

**Output**
```
console.log components/presentational/EthereumSignUpForm.test.js:35
    Address value:

 console.log components/presentational/EthereumSignUpForm.js:14
    Button pressed
```

**Solution:** Worked when calling the component function directly an then check address state value.

**Comment by pcowgill** [comment]
A) Thanks for the context on the choice between react-test-renderer create, react-test-renderer shallow, and Enzyme shallow. I think you made the right call.
B) It sounds like Expo 32 will most likely have that React Native bug fix. That should hopefully be out in a couple weeks based on their past release rhythm. https://github.com/expo/expo/pull/3014
C) Interesting, so we need some way to await all the results of the button press. I wonder if a couple wrapper.update's would have helped. Would making createAccount non-async have made this simpler? This is an interesting problem to keep in mind. Do you think it's worth creating an issue about this in this repo? It's good that calling the function directly worked. Nice work!

**Comment by marcelomorgado** [comment]
A) :+1:
B) Got it. Cool.
C) I've tried some tricks, but it didn't work. Yes, with non-async function it works well, I've just tried out here:
```
  createAccount = () => { this.setState({ address: "0x" }); };
```
Yes, I think that it's worth, how is the better way to do that? Creating a `tasit` new branch to reproduce all environment with the code above?

Thanks!

**Comment by pcowgill** [comment]
C) I think let's merge https://github.com/tasitlabs/tasit/pull/29, I'll create an issue for swapping the test to using the button press, and yeah this can come in a new branch off of develop after I merge that PR.

What did you mean by "reproduce all environment"?

**Comment by marcelomorgado** [comment]
> What did you mean by "reproduce all environment"?
Keep same setup, dependencies, versions.
