### ISSUE TITLE
Some land images aren't loading

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#134]
![Simulator Screen Shot - iPhone XR - 2019-03-13 at 09 29 12](https://user-images.githubusercontent.com/29674218/54287786-3eaa2c80-459e-11e9-9fb9-4a32899d4719.png)

**Comment by marcelomorgado** [comment]
I've queried a range of estate ids using the URL `https://api.decentraland.org/v1/estates/ID/map.png`:
Estate IDs with image: 1,2,3,6,8
Estate IDs without image: 4,5,7,9,10

**Comment by pcowgill** [comment]
Ah ok, good to know. So we'll avoid using the ones without images I guess?

**Comment by marcelomorgado** [comment]
Yes, I'll refine the `populateDecentralandContracts` to avoid those without images.

**Comment by pcowgill** [comment]
> Yes, I'll refine the `populateDecentralandContracts` script to avoid those without images.

Perfect, thanks
