### ISSUE TITLE
Update the linting rules and update the components to adhere to the new rules

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#14]
https://github.com/tasitlabs/tasit/pull/13#issuecomment-443866741

How can we do about current [console.log](https://github.com/tasitlabs/tasit/blob/develop/demo/App.js#L13). Could we display wallet address on screen? Any better idea?

**Comment by pcowgill** [comment]
Yeah, displaying it on the screen seems like a good plan!

**Comment by marcelomorgado** [comment]
Also upgrade eslint rules config to use words instead numbers.

**Comment by pcowgill** [comment]
@marcelomorgado I think this could be a good quick one to knock out soon

**Comment by pcowgill** [comment]
A few other thoughts on the linting settings for this issue:
https://github.com/tasitlabs/tasit/pull/26#discussion_r242397281
https://github.com/tasitlabs/tasit/pull/26#discussion_r242397420
https://github.com/tasitlabs/tasit/pull/26#discussion_r242397756

**Comment by marcelomorgado** [comment]
**- no-console**
There is one use of it now: https://github.com/tasitlabs/tasit/blob/aff489b2fb4d41cf15cd694840960bb49243708b/demo/App.js#L31
Can I comment that?

**- react-native/no-raw-text**
I've turned off this rule because I wanted that `<LargeText>` component behavior was as `<Text>`. Is be better with this will be turned on? If is the case, the large text component will be used that way:
```
<LargeText><Text>String</Text></LargeText>
```

**- jest/no-large-snapshots**
I've activated that rule because I've thought it interesting to help us to keep the components small. But seems that 20 lines could be too small. 6/7 snapshots are grater than 20 lines.

**Comment by pcowgill** [comment]
**no-console**
I'd slightly prefer to change the config for the no-console rule to allow warn and error for now. https://eslint.org/docs/rules/no-console

In the long run, we can make a logging helper that wraps the console.log / console.warn / etc. functions and only uses them when a dev env var is set to true.

**Comment by pcowgill** [comment]
**jest/no-large-snapshots**

Yes, let's change it to 40 or 50. How does that sound? Would the snapshots pass with that new rule?

**Comment by pcowgill** [comment]
**react-native/no-raw-text**
```
This rule has an object option:

    "skip" – allow to skip checking for the array of custom components
```

I think that should solve the problem!

**Comment by pcowgill** [comment]
For `react/prop-types`, if we don't want to fix it everywhere just yet after changing the rule, I'd rather have eslint single-or-multi-line disabling wherever we don't use prop-types instead of turning the rule off. That will give us a nice bit of code smell to remind us to fix this bit of tech debt in the future

**Comment by marcelomorgado** [comment]
> **jest/no-large-snapshots**
> 
> Yes, let's change it to 40 or 50. How does that sound? Would the snapshots pass with that new rule?

With 60 lines max, only one component doesn't pass (EthereumSignUpForm). That is nice because it is really big and should be a target of refactoring soon.

**Comment by pcowgill** [comment]
> With 60 lines max, only one component doesn't pass (EthereumSignUpForm). That is nice because it is really big and should be a target of refactoring soon.

That sounds perfect

**Comment by pcowgill** [comment]
@marcelomorgado Was it intentional that you did `refs` rather than `closes` for this PR? I think we can close this one.

**Comment by marcelomorgado** [comment]
No, it wasn't. Sorry. 
Yes, I agree.

**Comment by pcowgill** [comment]
No worries! I just wanted to confirm. Thanks!
