### ISSUE TITLE
Fix missing push notification entitlement on iOS

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#141]
Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

**Comment by pcowgill** [comment]
@marcelomorgado FYI I'm getting this warning every time I upload a new iOS build

**Comment by marcelomorgado** [comment]
Hey @pcowgill, seems this [post](https://github.com/expo/expo/issues/2092#issuecomment-469528206) is what we need to fix it. I've tried to follow the steps but seems that I haven't enough permissions to proceed.

**Comment by pcowgill** [comment]
@marcelomorgado Okay, thanks! I’ll look into this. Any idea what type of persmisson in particular was missing?

**Comment by marcelomorgado** [comment]
> @marcelomorgado Okay, thanks! I’ll look into this. Any idea what type of permisson in particular was missing?

> 4. Choose your app ID, edit it and check "Push Notifications". Save changes

All checks are disabled for me.

**Comment by pcowgill** [comment]
Thanks for checking.

Okay, I think this is all done now. I'll confirm the next time I upload an app version.

Their instructions involved the Mac app `Keychain Access` quite a bit, so it might not have worked on a Mac. For that reason, I don't think it's worth the time to figure out how to give you these specific Apple permissions

**Comment by marcelomorgado** [comment]
> Thanks for checking.
> 
> Okay, I think this is all done now. I'll confirm the next time I upload an app version.
> 
> Their instructions involved the Mac app `Keychain Access` quite a bit, so it might not have worked on a Mac. For that reason, I don't think it's worth the time to figure out how to give you these specific Apple permissions

Agree

**Comment by pcowgill** [comment]
Note: The certificate I generated may or may not work for local development using push notifications. If it doesn't, I can generate another for that environment

**Comment by pcowgill** [comment]
Hmm, I still got the alert, so there's more to be done.

I think we need to run `expo build:ios -c --no-publish` to clear the expired credentials and generate new ones now that I've added the push notification credentials. I'll try that now.

**Comment by pcowgill** [comment]
FYI edited the comment above ^

**Comment by pcowgill** [comment]
I manually deleted the provisioning profile that had become invalid from within the apple developer portal and then did:

```
npx expo fetch:ios:certs
npx expo build:ios --clear-push-cert
npx expo build:ios --clear-provisioning-profile
```

So far that seems promising. Uploading the new version now.

**Comment by pcowgill** [comment]
This is working now. Closing this.

**Comment by maharjanaman** [comment]
I'm still getting this error for my new builds. I let expo handled all the certificates. I'm able to enable Push Notifications from developers account but didn't recreate the certificates. Can we not use certificates created by expo???

**Comment by pcowgill** [comment]
@maharjanaman In my experience we had to delete the provisioning profile either manually from within the Apple UI or using the Expo commands (I tried both at once so I’m not sure what fixed it). Then you let Expo regenerate a new one for you after having changes the push notification setting.

**Comment by maharjanaman** [comment]
@pcowgill by provisioning profile, did you mean all certificates generated by expo? If yes, if we regenerate new ones, don't we again have to enable push notifications from developers account?

**Comment by pcowgill** [comment]
@maharjanaman At this URL developer.apple.com/account/ios/certificate/?teamId=**[REDACTED]**

Note that you'll need to use the right teamId above ^

there's a section at the lower left called `Provisioning Profiles`. The distribution profile shown there is the one I manually deleted. The `App ID` we modified in the `App IDs` section under `Identifiers` on that page (based on the instructions [here](https://github.com/expo/expo/issues/2092#issuecomment-469528206) should not be deleted, and it's not deleted by any of the expo commands above.
