### ISSUE TITLE
Submit "Decentraland by Tasit" to Apple for beta app review

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#142]

**Comment by pcowgill** [comment]
This issue is gated by https://github.com/tasitlabs/tasit/issues/143

**Comment by pcowgill** [comment]
Going through beta app review will allow us to share the app with external beta testers through TestFlight without adding the users to our App Store Connect organization

**Comment by marcelomorgado** [comment]
This issue can be closed?

**Comment by pcowgill** [comment]
Yep!
