### ISSUE TITLE
Land for sale not loading on iOS app distributed through TestFlight despite it working on simulator

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#143]
![IMG_3668](https://user-images.githubusercontent.com/2731712/54458118-2585b500-4731-11e9-9c31-c91991cda7c5.PNG)

**Comment by pcowgill** [comment]
@marcelomorgado Any ideas on a next step for debugging this?

**Comment by marcelomorgado** [comment]
Hmmm not really. There is some way to get access to some kind of debug log?

**Comment by pcowgill** [comment]
@marcelomorgado Yeah, I’ll look into our best options for that. There are a few things I have done in the past to debug production builds.

In the meantime, can you see if this loads for you and works on Android in the Expo app? https://expo.io/@tasit/tasit-decentraland

**Comment by marcelomorgado** [comment]
> @marcelomorgado Yeah, I’ll look into our best options for that. There are a few things I have done in the past to debug production builds.
> 
> In the meantime, can you see if this loads for you and works on Android in the Expo app? https://expo.io/@tasit/tasit-decentraland

Not working here.

**Comment by pcowgill** [comment]
In that case, I wonder if it has something to do with the production settings / or config variables when I published the js assets. Feel free to try publishing with the `tasit` Expo credentials from your machine to see if that changes anything.

**Comment by marcelomorgado** [comment]
Sorry, but which app we should publish right now? From `develop` branch or from `no-blockchain` branch?

**Comment by pcowgill** [comment]
I was publishing from `develop` based on our discussion here https://github.com/tasitlabs/tasit/issues/64#issuecomment-473355679

**Comment by pcowgill** [comment]
@marcelomorgado Niiice, it's workin now as of build 0.0.2!

![IMG_3684](https://user-images.githubusercontent.com/2731712/54714695-8f320480-4b1f-11e9-8216-1972dddb7000.PNG)
