### ISSUE TITLE
Prepare ropsten funds and data

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#156]
We should have 100 assets for sale (parcels + estates)
We should allow 200 ephemeral uses (each one with 0.05 ethers and 10 Mana tokens)

Said that:
Fund [Gnosis Safe wallet](https://ropsten.etherscan.io/address/0xdF1108C839686f28b5010a1784a07262aA447722) with at least 10 ethers and 2000 Mana tokens.
The [Gnosis safe wallet owner](https://ropsten.etherscan.io/address/0x82ec22bdb87aadceab9afeec87f17dbbd5e0a1c1) should have enough ether to pay for all fund transactions gas. 2 ethers (200 * 0.01) should be more than enough.

**Comment by pcowgill** [comment]
Maybe each asset should cost a lot more than 10 MANA tokens to match real prices on mainnet. Maybe more like 10,000 MANA each?

**Comment by marcelomorgado** [comment]
I've funded Gnosis Safe wallet with a billion mana tokens ([tx](https://ropsten.etherscan.io/tx/0xd08ce83cc65efc8f6168a198899735d99eecd086652fab97c92e7be2da7207a7))
I can create prices using this rule: [a rand number between 10 to 100] * 1000 MANA. 
In the worst case, it can allow 10k purchases. What do you think?

**Comment by pcowgill** [comment]
> I've funded Gnosis Safe wallet with a billion mana tokens ([tx](https://ropsten.etherscan.io/tx/0xd08ce83cc65efc8f6168a198899735d99eecd086652fab97c92e7be2da7207a7))
> I can create prices using this rule: [a rand number between 10 to 100] * 1000 MANA.
> In the worst case, it can allow 10k purchases. What do you think?

Sounds good!

**Comment by marcelomorgado** [comment]
[Gnosis safe wallet](https://ropsten.etherscan.io/address/0xdF1108C839686f28b5010a1784a07262aA447722) is now with 11.8 ethers.
[Gnosis safe wallet owner/signer](https://ropsten.etherscan.io/address/0x82ec22bdb87aadceab9afeec87f17dbbd5e0a1c1) is now with 2 ethers.

**Comment by marcelomorgado** [comment]
Extracted the remaining task to https://github.com/tasitlabs/TasitSDK/issues/285 since that will change a script of the `TasitSDK` repo.
I think that could close this one.

**Comment by pcowgill** [comment]
> Extracted the remaining task to https://github.com/tasitlabs/TasitSDK/issues/285 since that will change a script of the `TasitSDK` repo.
I think that could close this one.

Yep. Great work!
