### ISSUE TITLE
Insufficient funds error transiently shows up while account is being generated

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#169]
![Screenshot 2019-03-20 12 40 19](https://user-images.githubusercontent.com/2731712/54706786-b8e23000-4b0d-11e9-9990-087bca74761f.png)

**Comment by marcelomorgado** [comment]
I'm almost sure that it happened because you used a version of the code with the old private key of the Gnosis Safe wallet owner.

**Comment by pcowgill** [comment]
@marcelomorgado Could be. But it went away after a bit and there were sufficient funds, I think. All I would need to do is run the latest version of develop, right? Or are there any cleaning steps I would need to do to purge the app of that old private key?

**Comment by marcelomorgado** [comment]
Just the last `develop` version. I'll make more tests here but until now since `0.0.2` that I'm using, the only problem that I've identified is that about `bad instruction`.

**Comment by pcowgill** [comment]
@marcelomorgado Okay I'll try it again now. When's the last time you deleted the app and reinstalled it and created a new account by saying `Yep`?

**Comment by marcelomorgado** [comment]
> @marcelomorgado Okay I'll try it again now. When's the last time you deleted the app and reinstalled it and created a new account by saying `Yep`?

About 15min ago

**Comment by pcowgill** [comment]
@marcelomorgado I was able to reproduce it again on iOS with the latest version of develop. Here's the full screenshot.

![Simulator Screen Shot - iPhone XR - 2019-03-20 at 13 56 44](https://user-images.githubusercontent.com/2731712/54711517-1bd8c480-4b18-11e9-99e2-e0735d62ac46.png)

I'll try it on the Android emulator to see if the results are different.

**Comment by marcelomorgado** [comment]
OK, thanks :+1:

**Comment by pcowgill** [comment]
@marcelomorgado I also was able to reproduce it on Android on the Genymotion emulator for a Google Pixel 2 on my machine

![Screenshot 2019-03-20 14 03 37](https://user-images.githubusercontent.com/2731712/54711998-352e4080-4b19-11e9-8df9-ba49560b027e.png)

It's possible it relates to me not being able to enter a username https://github.com/tasitlabs/tasit/issues/168, but that seems unlikely

**Comment by marcelomorgado** [comment]
I'm working on the tests right now

**Comment by pcowgill** [comment]
@marcelomorgado FYI if I dismiss the error and then wait for the `WAITING FOR ACCOUNT...` button to change to a `BUY` button, it does appear to eventually work and have enough funds. So I think the code that triggers the alert is just checking if there are enough funds too early

**Comment by marcelomorgado** [comment]
> @marcelomorgado FYI if I dismiss the error and then wait for the `WAITING FOR ACCOUNT...` button to change to a `BUY` button, it does appear to eventually work and have enough funds. So I think the code that triggers the alert is just checking if there are enough funds too early

Fixed and explained on the PR #174
