### ISSUE TITLE
Show ephemeral account address and/or link to Etherscan transactions from within app

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#173]

**Comment by pcowgill** [comment]
This is mostly for trying things out while testing the app and less of a "production-ready" feature

**Comment by pcowgill** [comment]
@marcelomorgado One other benefit of this feature is that our alpha and beta testers trying the app would be able to confirm for themselves that indeed the back-end blockchain-related features are working as expected

**Comment by marcelomorgado** [comment]
I'll work on that as my next issue.

**Comment by marcelomorgado** [comment]
Where this link should be shown?

**Comment by pcowgill** [comment]
> Where this link should be shown?

I'll be thinking about this shortly, and I'll let you know!

**Comment by pcowgill** [comment]
@marcelomorgado I just added some rough thoughts about this in the `#design` channel on Slack, and once we come to a decision I'll post that here.

**Comment by marcelomorgado** [comment]
After a discussion on Slack, we've decided these:

- Account setup transactions `etherscan` links should be shown on each step message;
- Move the user to `MyLandScreen` after purchase;
- On the `MyLandScreen`, show buy tx `etherscan` links below each parcel of land (using an eye icon);

**Comment by marcelomorgado** [comment]
After purchase, if the user clicks on the `Land For Sale` menu item, he will be moved to the `BuyLandScreen` showing the asset already bought, It's a bug. The menu link 'Land for Sale' should move the user to the `LandForSaleListScreen`.

**Comment by marcelomorgado** [comment]
@pcowgill commented about design:
> I’m thinking the eye for the link to each land tx can go to the lower right of the land image, right-aligned with the right side of the land image, with a little spacing between the land image and the eye

**Comment by pcowgill** [comment]
> After purchase, if the user clicks on the `Land For Sale` menu item, he will be moved to the `BuyLandScreen` showing the asset already bought, It's a bug. The menu link 'Land for Sale' should move the user to the `LandForSaleListScreen`.

Should we split this out into a separate issue?

**Comment by marcelomorgado** [comment]
> > After purchase, if the user clicks on the `Land For Sale` menu item, he will be moved to the `BuyLandScreen` showing the asset already bought, It's a bug. The menu link 'Land for Sale' should move the user to the `LandForSaleListScreen`.
> 
> Should we split this out into a separate issue?

Okay. Extracted to: https://github.com/tasitlabs/tasit/issues/267

**Comment by marcelomorgado** [comment]
Updating the TODO list for this issue:

~~- Account setup transactions `etherscan` links should be shown on each step message;~~ Done
~~- Move the user to `MyLandScreen` after purchase;~~ Extracted https://github.com/tasitlabs/tasit/issues/267
- On the `MyLandScreen`, show buy tx `etherscan` links below each parcel of land (using an eye icon);

**Comment by pcowgill** [comment]
@marcelomorgado Let's reopen this until we get the eye fully right-aligned with the land image

![Simulator Screen Shot - iPhone Xʀ - 2019-04-18 at 09 47 35](https://user-images.githubusercontent.com/2731712/56369621-5721ee00-61bf-11e9-884a-a86e68e183d4.png)
