### ISSUE TITLE
Change Android icon to an opaque circular logo with a transparent background behind it

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#186]

**Comment by pcowgill** [comment]
![Screenshot_20190321-174036](https://user-images.githubusercontent.com/2731712/54789568-e360e580-4c00-11e9-8e93-f6fd224466cf.png)

**Comment by marcelomorgado** [comment]
Here the icon is looking that way:
![TasitApp](https://user-images.githubusercontent.com/29674218/55472416-f5c91f00-5603-11e9-9989-13393b00a34c.png)

**Comment by pcowgill** [comment]
@marcelomorgado Thanks for checking. I was going to look on my Android device after it recharged enough to turn on. Looks like a different PNG that’s more “zoomed out” will do the trick as an adaptive icon.

Android 8.0 (API level 26) introduces adaptive launcher icons - my personal testing android device is on Android 7.1, and there it still looks like a square. So while I'm redoing the adaptive icon, I'll add one more icon option for Android devices running older software as well.

**Comment by pcowgill** [comment]
It's looking better now on Android 7.1.

I might want to change the alignment slightly to leave more space at the upper right, but we can create a separate issue for that.
![Screenshot_20190403-113135 copy](https://user-images.githubusercontent.com/2731712/55496334-6ec87680-5604-11e9-8ae5-550ac280647b.png)


![Screenshot_20190403-113135](https://user-images.githubusercontent.com/2731712/55496312-5ce6d380-5604-11e9-9983-3b11b8f98b9b.png)

**Comment by pcowgill** [comment]
@marcelomorgado Once you update your app on your Android device to `0.0.12`, can you send a screenshot of how the icon looks for you now? Thanks!

**Comment by marcelomorgado** [comment]
I don't how long it takes to update because it stays the same just after the update, but after restart the device, the icon was updated:

![WhatsApp Image 2019-04-03 at 5 48 31 PM](https://user-images.githubusercontent.com/29674218/55497381-28d9d580-5639-11e9-9d8a-3502312145b3.jpeg)

**Comment by pcowgill** [comment]
> I don't how long it takes to update because it stays the same just after the update, but after restart the device, the icon was updated:

It's surprising it behaves that way, but I'd say it looks pretty good now that it did update. Maybe if you uninstalled the app first it would have updated right away.
