### ISSUE TITLE
Persist ephemeral account between app quitting and reopening

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#190]

**Comment by pcowgill** [comment]
@marcelomorgado As of right now, is it persisted when the app is quit and reopened without a version update?

**Comment by marcelomorgado** [comment]
> @marcelomorgado As of right now, is it persisted when the app is quit and reopened without a version update?

No, not really the created account is lost after closing the app (from the background).

**Comment by pcowgill** [comment]
Okay good to know, thanks. In that case I think it is a slightly higher priority than I originally thought
