### ISSUE TITLE
Assests for sale list is duplicating after refreshing

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#193]
After refreshing the main list (backing to the home screen and loading again), the asses are being appended to the already loaded list and duplicated it.

Note: Maybe this issue will be deprecated after [Git rid of loading screen since it's serving a duplicate role with the Expo splash screen](https://github.com/tasitlabs/tasit/issues/166)

**Comment by pcowgill** [comment]
Should we close this as a duplicate of https://github.com/tasitlabs/tasit/issues/167 ?

**Comment by marcelomorgado** [comment]
Oh, yes. For sure.
Closing this.
