### ISSUE TITLE
While waiting for account to be ready, show alert messages at each bit of progress

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#199]
(Account generation complete + after each tx.)

**Comment by pcowgill** [comment]
@marcelomorgado So far this step has taken longer than early testers expected, so I think this would be a good quick win

**Comment by pcowgill** [comment]
The longer-term solution will be something like this - https://github.com/tasitlabs/tasit/issues/188 - but having a good sense of timing for each step will help with that

**Comment by pcowgill** [comment]
The UX is sooo much better now after this change

**Comment by marcelomorgado** [comment]
Great!
