### ISSUE TITLE
Change title bar color at the top of app to match main background color

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#201]
And maybe default the app in general to dark mode?

**Comment by pcowgill** [comment]
Marcelo is going to see how white looks for the title bar

**Comment by marcelomorgado** [comment]
I think this can be closed since the header is already white and it seems good.

**Comment by pcowgill** [comment]
Agreed - I just added a `Closes` to the description of this PR https://github.com/tasitlabs/tasit/pull/224
