### ISSUE TITLE
Purchased assets should show up after app reload - load “my assets” list from blockchain

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#210]
For now, an asset is added to `my assets` list by `redux` after the user bought it.
Since we'll persist the ephemeral account, we should load the list every time the user starts the app.

Gated by  #190

Make sense that this data from `Decentraland API` or it should be getting from the `EstateRegistry` and `LandRegistry` contracts?

**Comment by marcelomorgado** [comment]
Maybe use local storage for that?

**Comment by pcowgill** [comment]
> Maybe use local storage for that?

Persisting the assets to local storage to show until the new list ends up updating (nice on subways without cell reception, etc.) and only showing new ones if the new list that was fetched differs from the local list sounds good.

> Make sense that this data from `Decentraland API` or it should be getting from the `EstateRegistry` and `LandRegistry` contracts?

If it's almost as performant as using the API, I'd rather use contracts directly if possible.

If hitting the contracts directly is prohibitively slow or uses a lot of data (bad on a cellular connection) or a lot of battery (unlikely but worth checking since this would be bad on mobile), it's nice if we can try to find solutions that generalize to other dapps too like an indexing service if possible. The more decentralized or planning-to-decentralize the indexing service is, the better.

**Comment by marcelomorgado** [comment]
Nice! :+1: :v:

**Comment by pcowgill** [comment]
@marcelomorgado Feel free to use the `decentraland` GitHub issue label rather than prefixing the issue name with Decentraland

**Comment by pcowgill** [comment]
> Persisting the assets to local storage to show until the new list ends up updating (nice on subways without cell reception, etc.) and only showing new ones if the new list that was fetched differs from the local list sounds good.

Note that there's likely a library we'll want to leverage to help with this

**Comment by pcowgill** [comment]
@marcelomorgado Note that until we do this, after you successfully buy land, if you quit the app and reopen it, the land no longer is there on the `My Assets` screen

**Comment by pcowgill** [comment]
@marcelomorgado Would getting my assets list from `Decentraland API` even work on testnet?

**Comment by marcelomorgado** [comment]
> @marcelomorgado Would getting my assets list from `Decentraland API` even work on testnet?

Oh, good point. No, not really, my fault.

**Comment by marcelomorgado** [comment]
> @marcelomorgado Note that until we do this, after you successfully buy land, if you quit the app and reopen it, the land no longer is there on the `My Assets` screen

Yes, I've created this issue because of that. Actually, since the current app is creating a new ephemeral account on each start it weirdly isn't a bug, but it will after account persistence (#190).

**Comment by pcowgill** [comment]
Ah yes, makes sense!

**Comment by pcowgill** [comment]
@marcelomorgado I think we should prioritize this issue since it’s one of the most likely to confuse our beta testers

**Comment by marcelomorgado** [comment]
OK :+1:

**Comment by marcelomorgado** [comment]
I'll work on this, just after finishing open PRs.

**Comment by pcowgill** [comment]
> I'll work on this, just after finishing open PRs.

Sounds good - thanks!

**Comment by marcelomorgado** [comment]
- EstateRegistry contract doesn't have a method to get all estate IDs owned by an address
- LandRegistry contract has the _assetsOf[owner] array, but it's internal
- LandRegistry contract has the landOf(address owner) method but it's returns x,y array but only of parcels that don't belong to any estate.


```javascript
// Getting parcels from an account - A possible implementation 
const getParcelsOf = async address => {
  const coords = await landContract.landOf(address);
  let parcels = [];
  for(let i = 0; i < coords.length; ++i) {
    let x = coords[0][i];
    let y = coords[1][i];
    let id = await landContract.encodeTokenId(x, y);
    let name = await landContract.tokenMetadata(id);
    let parcel = { id, x, y, name };
    parcels.push(parcel);
  }
  return parcels;
}

// Getting estates from an account - WIP
```

**Comment by marcelomorgado** [comment]
Maybe, another way to get that is using events:
`assetsOf = (All transfer events to address) - (All transfer events from address)`
Since marketplace order execution call tokens transfer functions.

**Comment by marcelomorgado** [comment]
Go deep on the last solution (using events):

**EstateRegistry**
`mint()` emits `Transfer` event (from `0` to address) :heavy_check_mark: 
`burn()` emits `Transfer` event (from address to `0`) :heavy_check_mark: 
`transferFrom()` emits `Transfer` event :heavy_check_mark: 
`safeTransferFrom` emits `Transfer` event :heavy_check_mark: 
`transferLand` emits `Transfer` event :heavy_check_mark: 
`transferManyLands` emits `Transfer` event :heavy_check_mark: 
`safeTransferManyFrom` emits `Transfer` event :heavy_check_mark: 

**LandRegistry**
`safeTransferFrom`  emits `Transfer` event :heavy_check_mark: 
`transferFrom`  emits `Transfer` event :heavy_check_mark: 
`assignNewParcel` emits `Transfer` event :heavy_check_mark: 
`assignMultipleParcels` emits `Transfer` event (one for each parcel) :heavy_check_mark: 
`transferLand` emits `Transfer` event :heavy_check_mark: 
`transferManyLand` emits `Transfer` event (one for each parcel) :heavy_check_mark: 

**Marketplace**
Calls `ERC20.transferFrom()` :heavy_check_mark: 
Calls `ERC721.safeTransferFrom()` :heavy_check_mark: 

Note:
When a parcel is moved to an estate (`transferManyLandToEstate` function) the new owner of the parcel becomes the `EstateRegistry` contract, it isn't a problem, it's how the Decentraland business logic works: If you are a owner of an estate, you balance is only the estate, its parcels are removed from your `LandRegistry` balance.

**Comment by pcowgill** [comment]
Yep, I agree that without the `ERC721Enumerable` (using OpenZeppelin's implementation as an example) methods available in the Decentraland ERC721-related contracts (and they aren’t available there), constructing ownership state from past events is the way to go!

**Comment by marcelomorgado** [comment]
Gated by https://github.com/tasitlabs/TasitSDK/issues/300

**Comment by pcowgill** [comment]
This was accidentally closed because the other PR had the `closes` keyword in it

**Comment by marcelomorgado** [comment]
Ouch
