### ISSUE TITLE
The account should be stored after all setup process?

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#230]
The current account creation process is storing the account before setup (funding and approval) became complete. Should the account store only be done after all setup process?

**Comment by pcowgill** [comment]
Hmm, what would be the argument for waiting? I think it still could make sense to have the UI already start showing the address where appropriate, etc.

**Comment by pcowgill** [comment]
If you agree, feel free to close this

**Comment by marcelomorgado** [comment]
Ok. Closing.
