### ISSUE TITLE
The “approving marketplace” message didn’t go away after approving the marketplace finished according to the alert

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#234]

**Comment by pcowgill** [comment]
@marcelomorgado There's one remaining change we may want to make here.

When it's at the stage where it's going to fund the account with MANA and approve the marketplace in parallel, shouldn't it say when both begin something like `Approving marketplace and funding with MANA...`?

Here's the flow I just saw, which seemed to assume in the flow that marketplace approval would happen first.

![Simulator Screen Shot - iPhone Xʀ - 2019-04-01 at 13 20 51](https://user-images.githubusercontent.com/2731712/55350810-8d066900-5482-11e9-9521-0977f109799e.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-04-01 at 13 21 14](https://user-images.githubusercontent.com/2731712/55350839-97286780-5482-11e9-81c6-4937b46e7abc.png)

**Comment by marcelomorgado** [comment]
Oh yeah, this message is missing.

**Comment by pcowgill** [comment]
> Oh yeah, this message is missing.

@marcelomorgado FYI I'm working on this.

**Comment by pcowgill** [comment]
@marcelomorgado Nice, this is working perfectly now:

![Simulator Screen Shot - iPhone Xʀ - 2019-04-03 at 11 11 19](https://user-images.githubusercontent.com/2731712/55495123-d8935100-5601-11e9-9c31-15d369767925.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-04-03 at 11 12 39](https://user-images.githubusercontent.com/2731712/55495128-dc26d800-5601-11e9-905b-a9ccaf73d061.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-04-03 at 11 12 47](https://user-images.githubusercontent.com/2731712/55495134-df21c880-5601-11e9-931d-b62727972de6.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-04-03 at 11 13 11](https://user-images.githubusercontent.com/2731712/55495141-e1842280-5601-11e9-8d4c-22ae3b91571e.png)

**Comment by marcelomorgado** [comment]
Great!
