### ISSUE TITLE
After purchase navigation

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#267]
After purchase, user is being moved to `ListLandForSaleScreen`, to improve the UI flow, that navigation should be change to redirect the user to `MyAssetsScreen`.
We've made a tryout on that and faced some issues that need to me addressed:

- After purchase, if the user clicks on the `Land For Sale` menu item, he will be moved to the `BuyLandScreen` showing the asset already bought, It's a bug. The menu link 'Land for Sale' should 
move the user to the `LandForSaleListScreen`.

- Since we are getting the list of users' land from blockchain during `MyAssetsScreen.componentDidMount` what is happening is:
On the first time of the app: User signs up, buy land and before the purchase process finished on the blockchain, he is moved to the `MyAssetsScreen` that will get no assets from blockchain and the list will be empty.
On the second use, the list will be loaded with the land bought on first use and so on...
The expected behavior only will happen if the user access the `MyAssetsScreen` before purcharse any asset.

**Comment by marcelomorgado** [comment]
To address the second problem, should we load assets on app startup (from App.js) or add a `status` field to the `myAssets` state and keep them during the reload from blockchain?

**Comment by pcowgill** [comment]
> To address the second problem, should we load assets on app startup (from App.js) or add a `status` field to the `myAssets` state and keep them during the reload from blockchain?

Yeah, this fix seems important. Maybe doing both would be a good defensive programming practice.

Do you think fetching them on app startup should gate the app finishing loading or no? I could see an argument either way.

**Comment by marcelomorgado** [comment]
I'm not sure if fetching on startup will gate the app but it'll at least use more network resources.
I'm thinking to add the `status` field for now because it should be enough to solve this bug.

**Comment by pcowgill** [comment]
> I'm not sure if fetching on startup will gate the app but it'll at least use more network resources.

I think in some cases using more network resources to improve UX is worth it if there's a >70% chance the user will experience that screen.

> I'm thinking to add the `status` field for now because it should be enough to solve this bug.

Sure, that sounds good.

**Comment by pcowgill** [comment]
I think the pattern to follow here is that there's a redux state update for each network request when request is initiated, when it succeeds, and when it fails due to timeout or error.
