### ISSUE TITLE
No large snapshot - move rule to error level

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#268]
We've setup the [`jest/no-large-snapshots`](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-large-snapshots.md) rule on our `eslint` and it's warning during the current test suite: 

> /.../tasit/decentraland/components/presentational/__snapshots__/**BuyLand**.test.js.snap
   87:1  warning  Expected Jest snapshot to be smaller than 50 lines but was 52 lines long  jest/no-large-snapshots
  141:1  warning  Expected Jest snapshot to be smaller than 50 lines but was 52 lines long  jest/no-large-snapshots
  195:1  warning  Expected Jest snapshot to be smaller than 50 lines but was 52 lines long  jest/no-large-snapshots
  249:1  warning  Expected Jest snapshot to be smaller than 50 lines but was 52 lines long  jest/no-large-snapshots
  303:1  warning  Expected Jest snapshot to be smaller than 50 lines but was 52 lines long  jest/no-large-snapshots
> 
> /.../tasit/decentraland/components/presentational/__snapshots__/**LandForSaleInfo**.test.js.snap
  3:1  warning  Expected Jest snapshot to be smaller than 50 lines but was 69 lines long  jest/no-large-snapshots

As I remember our motivation to turn this on is the avoid large components it still a valid motivation but these snapshots are large because we wrote many test cases for each one, there is no rule such as `no-large-snapshot-per-testcase`.
Here is a quote extracted from the rule description:

> As a best practice snapshots should be limited in size in order to be more manageable and reviewable.

Said that, should we change the way that we're testing our components keeping less test cases or increment the lines of each snapshot should have?

**Comment by pcowgill** [comment]
Hmm, but if that’s the case, why are there multiple warnings in the same snapshot for BuyLand?

**Comment by pcowgill** [comment]
I think it is only applying this rule separately to each individual test case, which is what we want.

**Comment by marcelomorgado** [comment]
> Cool, no worries. If we wanted to change the max snapshot size to 55 to allow those snapshots of size 52, that would be fine with me.

Fortunately, my last change on current PR solved it. If it occurs again I know that increase a little bit the size won't be a problem. Thanks!

**Comment by pcowgill** [comment]
> > Cool, no worries. If we wanted to change the max snapshot size to 55 to allow those snapshots of size 52, that would be fine with me.
> 
> Fortunately, my last change on current PR solved it. If it occurs again I know that increase a little bit the size won't be a problem. Thanks!

Okay, sounds good! I'd even be open to making that rule an error-level warning to make sure we track it.

**Comment by marcelomorgado** [comment]
> Okay, sounds good! I'd even be open to making that rule an error-level warning to make sure we track it.

Okay, I'm reopening this to address that.
