### ISSUE TITLE
Link to privacy policy from within the app

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#277]
https://privacy.tasit.io

**Comment by pcowgill** [comment]
@marcelomorgado Any thoughts on what screen this would be most appropriate in? The drawer menu seems to make the most sense, but I'm not sure off the top of my head how hard it would be to add a custom link there that doesn't navigate to another screen. Thoughts?

**Comment by marcelomorgado** [comment]
The drawer menu seems a good place for it. I've done a quick research on that and seems that will possible that we'll need to move the drawer to a custom component to achieve that. If I'm right, will'll spend more time than add a simple link but on the other hand, it could solve the `toast` problem.

**Comment by pcowgill** [comment]
@marcelomorgado Maybe in the interest of getting something out quickly we can just put it on the `EthereumQuestion` screen and change it later

**Comment by pcowgill** [comment]
Or actually maybe the `OnboardingHome` screen
