### ISSUE TITLE
Update the linting rules and update the components to adhere to the new rules

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#28]
https://github.com/tasitlabs/tasit/pull/26#discussion_r242397281
https://github.com/tasitlabs/tasit/pull/26#discussion_r242397420
https://github.com/tasitlabs/tasit/pull/26#discussion_r242397756

**Comment by marcelomorgado** [comment]
Refs: Modify App.js to pass on linting warnings #14

**Comment by pcowgill** [comment]
@marcelomorgado Good call, this is related enough to that existing issue that it belongs in there. I'll move these links over to that issue.
