### ISSUE TITLE
Force account removal after app uninstallation

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#295]
iOS is keeping the user's account after app uninstallation (Related to: https://github.com/tasitlabs/tasit/issues/289#issuecomment-483706543).
This behavior happens with `SecureStore` only. To solve it, alike `isFirstAppUse` should be persisted on `AsyncStore` and if the condition ` isFirstAppUse && retrieveEphemeralAccount() != null` the stored account should be removed.

**Comment by pcowgill** [comment]
Might be worth noting for posterity that this issue is a short-term solution, and we might not keep this behavior in the long run

**Comment by pcowgill** [comment]
This PR is probably worth making this week

**Comment by pcowgill** [comment]
@marcelomorgado If it ends up being easier, a button on the my account screen that lets you manually purge your account would work too. That might even be a better UX

**Comment by pcowgill** [comment]
> @marcelomorgado If it ends up being easier, a button on the my account screen that lets you manually purge your account would work too. That might even be a better UX

Curious for your thoughts on this

**Comment by marcelomorgado** [comment]
> > @marcelomorgado If it ends up being easier, a button on the my account screen that lets you manually purge your account would work too. That might even be a better UX
> 
> Curious for your thoughts on this

I was thinking about it, maybe worth forcing the removal to keep the same behavior on both iOS/android.

**Comment by pcowgill** [comment]
> I was thinking about it, maybe worth forcing the removal to keep the same behavior on both iOS/android?

Yeah, that certainly will make it easier to give advice to testers of the app

**Comment by marcelomorgado** [comment]
Should we keep this open until this feature still under preparation?

**Comment by pcowgill** [comment]
> Should we keep this open until this feature still under preparation?

Up to you. We can also create a new issue.

**Comment by marcelomorgado** [comment]
Extracted to: https://github.com/tasitlabs/tasit/issues/338
