### ISSUE TITLE
Bump version and publish latest UI improvements and bux fixes

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#335]
Once https://github.com/tasitlabs/tasit/pull/333 and https://github.com/tasitlabs/tasit/pull/331 are merged

**Comment by pcowgill** [comment]
@marcelomorgado I think the last commit from this PR https://github.com/tasitlabs/tasit/pull/324 is the best one test to test an upgrade from to make sure there are no problems with the changes in persistent storage

**Comment by pcowgill** [comment]
So this commit `5cc4c82a7738a0747ab4535dc46531d91cc7c6cb`

**Comment by marcelomorgado** [comment]
Are we use that commit or the `develop` branch after merging fixes and reset accounts?

**Comment by pcowgill** [comment]
@marcelomorgado Oh, good question. I guess that branch may not have been up to date with develop before merging it. Did the fixes you have in mind hit develop before or after merging that PR? Either way, we'll want the last commit from right before we actually published

**Comment by pcowgill** [comment]
It does look like develop was merged into that branch though, so I think it should have most of the fixes you're referring to if they were in `develop` before that PR https://forum.aragon.org/t/funding-proposal-aragon-native-mobile-app/811/7?u=pcowgill

**Comment by marcelomorgado** [comment]
I think that I wasn't clear on my question.
I've meant if we will publish a new version from this commit https://github.com/tasitlabs/tasit/commit/5cc4c82a7738a0747ab4535dc46531d91cc7c6cb
Or using the updated code with last changes (account reset) from branch https://github.com/tasitlabs/tasit/pull/343
I've made that question because I've thought that commit has the `storeIsFirstUse(false)` command and it could be a problem with our intent to reset all accounts. But I've just realized that commit hasn't this command.

**Comment by pcowgill** [comment]
Oh no, we definitely wouldn't want to publish from 5cc4c82. That's the commit that I was saying represent what's already been published for testing the upgrade path. So we'd use that as the `BEFORE` in a `BEFORE` and `AFTER` data migration test on our devices before publishing.

We would want to publish the code with the last changes for sure.

Yeah, it would have been bad if we published an intermediate commit. And yeah, I think that commit was from before we made those changes.

**Comment by marcelomorgado** [comment]
Ohh I see.

**Comment by pcowgill** [comment]
@marcelomorgado So does that commit work as the `BEFORE` commit then? If so, I'll begin testing and use the open PR as the `AFTER` commit

**Comment by marcelomorgado** [comment]
Okay
