### ISSUE TITLE
Regressions in develop branch: No land purchase link for land purchased in old version. 25% account completeness for account set up in old version.

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#344]
Regressions in develop branch:

1. No land purchase link for land purchased in old version.

![Simulator Screen Shot - iPhone Xʀ - 2019-04-24 at 09 43 05](https://user-images.githubusercontent.com/2731712/56668702-9b0c6b80-6675-11e9-8cf0-963ba57e5a3c.png)

2. 25% account completeness for account set up in old version.

![Simulator Screen Shot - iPhone Xʀ - 2019-04-24 at 09 43 10](https://user-images.githubusercontent.com/2731712/56668701-9b0c6b80-6675-11e9-914a-abbc7ee00335.png)

**Comment by pcowgill** [comment]
To reproduce this:

* check out this commit 5cc4c82a7738a0747ab4535dc46531d91cc7c6cb
* run app
* set up account and buy land
* quit app on device
* stop app with expo-cli
* check out `feature/open-threads-pr-333`
* start app with expo-cli
* start app on device

**Comment by pcowgill** [comment]
One possibility to prevent this from being a time sink is to force reset the accounts of all testers with this upgrade

**Comment by marcelomorgado** [comment]
Here is the fix of both bugs: https://github.com/tasitlabs/tasit/pull/343/commits/0cb0df52f7192740b0a3b657968be424f9203566

The bug (2) is occurring because of buggy store code. Beucase of that I think that turn on our `isFirstUse` flag is a way to go. And reset all account from now. Right?

**Comment by pcowgill** [comment]
> Here is the fix of both bugs: [0cb0df5](https://github.com/tasitlabs/tasit/commit/0cb0df52f7192740b0a3b657968be424f9203566)
> 
> The bug (2) is occurring because of buggy store code. Beucase of that I think that turn on our `isFirstUse` flag is a way to go. And reset all account from now. Right?

Yep, agreed!

**Comment by pcowgill** [comment]
> > Here is the fix of both bugs: [0cb0df5](https://github.com/tasitlabs/tasit/commit/0cb0df52f7192740b0a3b657968be424f9203566)
> > The bug (2) is occurring because of buggy store code. Beucase of that I think that turn on our `isFirstUse` flag is a way to go. And reset all account from now. Right?
> 
> Yep, agreed!

@marcelomorgado So once you make that change I'll run another test as described earlier in this issue?

**Comment by marcelomorgado** [comment]
Okay

**Comment by pcowgill** [comment]
@marcelomorgado I think we can close this

**Comment by marcelomorgado** [comment]
Ok. Resolving.
