### ISSUE TITLE
Update to TasitSDK 0.0.18 and use the new API throughout

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#372]
The latest version of `tasit-sdk` has some break changes:
- `action.waitForNonceToUpdate()` is now `action.waitForOneConfirmation()`;
- `action` now is sent using `send()` function.
- `Contract.wallet` is now `Contract.account` (getWallet, setWallet, removeWallet functions).

**Comment by pcowgill** [comment]
Technically I already merged that greenkeeper PR to update the SDK to 0.0.18, so the main changes needed here are to use the new API

**Comment by pcowgill** [comment]
As of PR https://github.com/tasitlabs/tasit/pull/378,

~action.waitForNonceToUpdate() is now action.waitForOneConfirmation();~
~Contract.wallet is now Contract.account (getWallet, setWallet, removeWallet functions).~
~action now is sent using send() function.~

**Comment by pcowgill** [comment]
@marcelomorgado The other major change we forgot about is that function calls don't expect `gasParams` anymore

**Comment by pcowgill** [comment]
> @marcelomorgado The other major change we forgot about is that function calls don't expect `gasParams` anymore

I made this change in this PR https://github.com/tasitlabs/tasit/pull/386
