### ISSUE TITLE
Style the buttons

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#38]
Make them look like buttons with a colored fill as opposed to hyperlinks

![img_2911](https://user-images.githubusercontent.com/2731712/50182497-154a6f00-02d5-11e9-87f3-9c59fb0797e9.PNG)

**Comment by marcelomorgado** [comment]
Weird, here buttons are different:
![whatsapp image 2018-12-19 at 12 17 21 pm](https://user-images.githubusercontent.com/29674218/50219884-7f701c00-0388-11e9-9120-1f3d763cbd01.jpeg)

**Comment by pcowgill** [comment]
Haha I've got a GitHub nitpicky pro tip for the future: I don't know how easy this is on your machine, but now that screenshots are so big these days, I like to reduce the dimensions of the image to something smaller before posting on issues. Otherwise it's hard to read through an issue.

**Comment by pcowgill** [comment]
Yeah, it looks like React Native takes the stance that the an Android-ish and iOS-ish button should look different by default to match the look of each OS.

https://docs.expo.io/versions/v31.0.0/react-native/button

Let's create a Tasit button component that wraps and styled React Native buttons.
