### ISSUE TITLE
Change the header color throughout the app

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#39]
Let's set a header color that falls into the background a bit more. Let's still make sure the color comes from `constants/Colors.js`, of course.

![img_2908](https://user-images.githubusercontent.com/2731712/50182548-3ca13c00-02d5-11e9-861d-74ef6d56d563.PNG)

**Comment by pcowgill** [comment]
Oh, and if you don't already have Atom configured to highlight hex colors in the code with the color itself, I highly recommend it!

**Comment by pcowgill** [comment]
@marcelomorgado I think we can mark this as closed

**Comment by marcelomorgado** [comment]
Closing.
