### ISSUE TITLE
Deploy demo app to TestFlight

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#64]

**Comment by pcowgill** [comment]
@marcelomorgado If we can do this with hardcoded data, I think this is an even higher priority for demo purposes than running the Tasit SDk test suite against a testnet

I'm happy to help with this since I've deployed apps a lot before, and I have some experience (albeit less) with Fastlane

**Comment by marcelomorgado** [comment]
For Sure! I'll probably need some help.
A question: For now app is connecting to a local network IP running ganache. 
Isn't to have app running using testnet before deploy it?

**Comment by pcowgill** [comment]
Cool cool. I can set up the Apple Developer accounts and everything and send you an invite.

What I meant by hard-coding is that we could stub out responses from the "blockchain" just so we could at least show how the current UI looks. But only if that doesn't present too much additional hacking work that we'll have to undo right away.

**Comment by marcelomorgado** [comment]
Oh, I see. Sure! I can do it quickly.

**Comment by pcowgill** [comment]
@marcelomorgado FYI I'm working on this one

**Comment by pcowgill** [comment]
@marcelomorgado Is this the branch to work off of?

https://github.com/tasitlabs/tasit/tree/feature/no-blockchain

Do we have a good workflow for getting the changes we like from the develop branch into that branch?

**Comment by marcelomorgado** [comment]
Yes, that branch has the decentraland app without blockchain (for demo purposes).
Should we keep this kind of demo/branch even with testnet working?

**Comment by pcowgill** [comment]
@marcelomorgado Oh, I guess if testnet is stable enough we can just declare that branch obsolete

**Comment by pcowgill** [comment]
@marcelomorgado I just sent invites to both of us as internal testers through TestFlight, so I'm marking this as complete
