### ISSUE TITLE
Since name of the app is Tasit Decentraland, it's confusing for the word Decentraland to be the button

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#69]
![screenshot 2019-01-20 12 19 27](https://user-images.githubusercontent.com/2731712/51443414-24468780-1cae-11e9-9f4f-8f5e47f440f1.png)

**Comment by marcelomorgado** [comment]
What we should display instead of 'Decentraland'?

**Comment by pcowgill** [comment]
Decentraland should be in the same font, font size, and boldness as Tasit, or perhaps with different ones but still clearly text as opposed to a button.

Maybe there should be no button at all on this screen, and this shows as a second loading screen with a 1 second timeout
