### ISSUE TITLE
Use cross-platform UI components

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#88]
@pcowgill said recently:
> I recently heard from one engineer that he prefers react-native-elements to NativeBase

Some modules:
https://github.com/react-native-training/react-native-elements
https://github.com/IjzerenHein/react-native-magic-move
https://github.com/GeekyAnts/NativeBase

Note: I'm not sure which milestone that belongs.

**Comment by pcowgill** [comment]
0.2.0 seems like a reasonable milestone for this.

**Comment by pcowgill** [comment]
Cross-platform UI components:

https://github.com/react-native-training/react-native-elements
https://github.com/GeekyAnts/NativeBase

Motion / animations:
https://github.com/IjzerenHein/react-native-magic-move
https://popmotion.io/pose/learn/native-get-started/

**Comment by pcowgill** [comment]
I think we can extract the motion / animations into a different issue, since it's pretty unrelated

**Comment by marcelomorgado** [comment]
Extracted to: https://github.com/tasitlabs/tasit/issues/215

**Comment by pcowgill** [comment]
@marcelomorgado I think we can close this issue

**Comment by marcelomorgado** [comment]
Yes, I agree. Closing this.
