### ISSUE TITLE
Remove .tasitid.eth from the pick username screen

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/tasit#94]
The user shouldn't need to wonder what ENS is when doing this

**Comment by marcelomorgado** [comment]
The screen is showing:
`Cool. Let's start by picking your Tasit username.`
`[____].tasitid.eth`
`[Continue Button]`

What should be shown?
`Cool. Let's start creating an account.`
`[Continue Button]`
?

**Comment by pcowgill** [comment]
I think literally just the current screen without `.tasitid.eth`. This complexity can be hidden until it’s needed. Or in a clickable info icon.
