### ISSUE TITLE
Add UI error/loading feedbacks

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/tasit#95]
Worth move to cross-platform UI components (https://github.com/tasitlabs/tasit/issues/88) before that?

**Comment by pcowgill** [comment]
> Worth move to cross-platform UI components (#88) before that?

Yeah, I think making that change along with this one would make sense.

**Comment by pcowgill** [comment]
@marcelomorgado After a little more thought, I no longer think that this issue is that tightly coupled to cross-platform UI components. It's still useful to have an Expo warning or error even without cross-platform componenets in the meantime. Should we split the issues out?

**Comment by pcowgill** [comment]
I think the highest priority errors to show in the app are "blockchain not found' and "no assets found, so the Decentraland script probably wasn't run"

**Comment by pcowgill** [comment]
@marcelomorgado Ah, we don't need to split the issues out, because there already is a separate issue for cross-platform UI components. So let's have this issue just be about UI errors using expo console.warn and console.error

**Comment by marcelomorgado** [comment]
Using `console.error` the error is shown that way on the app:

![Screenshot_20190311-190658](https://user-images.githubusercontent.com/29674218/54150825-587a3100-4431-11e9-81b6-da21b047a2c6.jpg)

Is it fine or should I change to `console.warn` to show only on the console?

**Comment by pcowgill** [comment]
@marcelomorgado I think even `console.warn` shows up in yellow on the app less obtrusively but still in a way that's not acceptable for end users.

We can use errors this obtrusive only when the target audience is a developer who should know that something isn't configured correctly. If it's an error that we want to show an end users, yeah, we shouldn't use either console.warn or console.error but instead some third-party library. But that's in the medium term. In the short term it's fine even if this shows up.
